name: Deploy Go Lambda Function

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy Lambda
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.3 # Adjust as needed

      - name: Install Dependencies
        run: go mod tidy

      - name: Upload collector.yml to S3
        run: |
          aws s3 cp collector.yml s3://codepipeline-us-east-2-237656914886/go-oauth-apigw-authorizer-lambda/collector.yml

      - name: Build Go Binary
        run: |
          GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o bootstrap ./cmd/main.go
          zip main.zip bootstrap

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-2  # Change to your AWS region

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name go-oauth-apigw-authorizer-lambda \
            --zip-file fileb://bootstrap.zip